services:
# A Database to store your Django application data
- type: "web"
name: "rotaiq-backend"
env: "python"
buildCommand: "./build.sh"
startCommand: "gunicorn rotaiq.wsgi:application"
envVars:
- key: "SECRET_KEY"
generateValue: true
- key: "DATABASE_URL"
fromDatabase:
name: "rotaiq_db"
property: "connectionString"

  # Frontend Static Site
  - type: "static_site"
    name: "rotaiq-frontend"
    env: "node"
    staticPublishPath: "./frontend/build"
    buildCommand: "npm install && npm run build"
    pullRequestPreviewsEnabled: false # Change to true if you want preview deployments

# Database
databases:
  - name: "rotaiq_db"
