# Generated by Django 5.2.5 on 2025-08-24 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0003_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The unique name of the region.', max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='invitation',
            name='role',
            field=models.CharField(choices=[('head_office', 'Head Office'), ('region_manager', 'Region Manager'), ('branch_manager', 'Branch Manager'), ('employee', 'Employee'), ('floating_employee', 'Floating Employee')], default='employee', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('head_office', 'Head Office'), ('region_manager', 'Region Manager'), ('branch_manager', 'Branch Manager'), ('employee', 'Employee'), ('floating_employee', 'Floating Employee')], default='employee', help_text="The user's role (manager or employee).", max_length=30),
        ),
        migrations.AddField(
            model_name='branch',
            name='region',
            field=models.ForeignKey(help_text='The region this branch belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='shifts.region'),
        ),
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.ForeignKey(blank=True, help_text='The region a manager is associated with.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managers', to='shifts.region'),
        ),
    ]
