# Generated by Django 5.2.5 on 2025-08-24 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0004_region_alter_invitation_role_alter_user_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='claimed_by',
        ),
        migrations.AddField(
            model_name='shift',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_shifts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='branch',
            name='region',
            field=models.ForeignKey(default=1, help_text='The region this branch belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='shifts.region'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shift',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('claimed', 'Claimed'), ('filled', 'Filled')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(help_text="The user's first name.", max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(help_text="The user's last name.", max_length=50),
        ),
        migrations.CreateModel(
            name='ShiftClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='shifts.shift')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('shift', 'user')},
            },
        ),
    ]
