# Generated by Django 5.2.5 on 2025-08-27 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0005_remove_shift_claimed_by_shift_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='first_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='last_name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
